#!/bin/ash

# Enable and start the services
echo "Starting and enabling services..."
service mount-fix enable
service mount-fix-final enable
service mount-fix start
service mount-fix-final start
service mount-fix enable
service mount-fix-final enable


    # Determine firmware version based on mount state after start()
    if grep -qs '/usrdata' /proc/mounts; then
        # Check if /etc is still mounted (R02 keeps it, R01 unmounts it)
        if mount | grep -q "^/dev/ubi2_0 on /etc type ubifs"; then
            echo "R02 firmware scenario detected (/etc still mounted)."
            mount -o remount,rw /real_rootfs
            cp /etc/init.d/mount-fix /real_rootfs/etc/init.d/mount-fix
            cp /etc/init.d/mount-fix-final /real_rootfs/etc/init.d/mount-fix-final
            cp -P /etc/rc.d/S03mount-fix /real_rootfs/etc/rc.d/S03mount-fix
            cp -P /etc/rc.d/S13mount-fix-final /real_rootfs/etc/rc.d/S13mount-fix-final
            mount -o remount,ro /real_rootfs
        else
            echo "New R01 firmware scenario detected (/etc unmounted)."
            cp /etc/init.d/mount-fix /usrdata/etc/init.d/mount-fix
            cp /etc/init.d/mount-fix-final /usrdata/etc/init.d/mount-fix-final
            cp /etc/init.d/mount-fix /usrdata/overlay-work/etc-upper/init.d/mount-fix
            cp /etc/init.d/mount-fix-final /usrdata/overlay-work/etc-upper/init.d/mount-fix-final            
            cp -P /etc/rc.d/S03mount-fix /usrdata/etc/rc.d/S03mount-fix
	    cp -P /etc/rc.d/S03mount-fix /usrdata/overlay-work/etc-upper/rc.d/S03mount-fix
    	    cp -P /etc/rc.d/S13mount-fix-final /usrdata/etc/rc.d/S13mount-fix-final
    	    cp -P /etc/rc.d/S13mount-fix-final /usrdata/overlay-work/etc-upper/rc.d/S13mount-fix-final
        fi
    else
        echo "Old R01 firmware scenario detected (without /usrdata)."
        # no need for postinist here
    fi


echo -e "\e[32m sdxpinn-mount-fix installed! Here is the new file structure! \e[0m"
echo -e "\e[32m ============================================================ \e[0m"
mount && df -h
echo -e "\e[32m ============================================================ \e[0m"
echo -e "\e[32m sdxpinn-mount-fix installed! New file structure above! \e[0m"

exit 0

