#!/bin/ash

LOG_FILE="/tmp/pre-mount-fixinst.log"
# Initialize log
rm -f "$LOG_FILE" >/dev/null 2>&1
touch "$LOG_FILE"
# Redirect all output (stdout and stderr) to the log file
exec >>"$LOG_FILE" 2>&1


if grep -qs '/real_rootfs' /proc/mounts; then
    echo "Upgrade scenario detected."
    service mount-fix stop
    service mount-fix disable
    echo "Filesystem structure returned to Quectel Stock"
    echo "Backup exists at /usrdata/rootfs or /data/rootfs"
fi

# Remount original rootfs as read-write 
echo "Mounting / as read-write"
mount -o remount,rw /

echo "Preinst complete...."
echo "View Results here:..."
df -h && mount

exit 0
