#!/bin/ash


echo "Stopping any running QuecManager Services..."

service quecmanager_services stop
service quecmanager_cell_locking stop
service quecprofiles stop
service quecwatch stop
service quecmanager_logging stop

echo "Cleanup complete."
exit 0

